name: CI Pipeline

on:
  push:
    branches:
      - main
      - develop
      - 'feature/*'
  pull_request:
    branches:
      - develop
      - main

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      # 🧩 1. Baixar o código do repositório
      - name: Checkout do código
        uses: actions/checkout@v4

      # 🐍 2. Configurar Python 3.12.0
      - name: Configurar Python 3.12.0
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.0'

      # ⚡ 3. Cache de dependências (acelera builds)
      - name: Cache de dependências pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      # 📦 4. Instalar dependências do projeto
      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest flake8 pytest-cov

      # 🔍 5. Análise de estilo com Flake8 (lint)
      - name: Verificar estilo de código (Flake8)
        run: |
          flake8 app tests --ignore=E501,W503 --max-complexity=10 --count

      # 🧪 6. Rodar testes unitários para branches feature/*
      - name: Rodar testes unitários
        if: startsWith(github.ref, 'refs/heads/feature/')
        run: pytest tests/unit --maxfail=3 --disable-warnings -q

      # 🧩 7. Rodar testes completos (develop e main)
      - name: Rodar testes completos
        if: github.ref == 'refs/heads/develop' || github.ref == 'refs/heads/main'
        run: |
          pytest --cov=app --cov-report=xml --disable-warnings
